"""added unique constraint to author

Revision ID: 748af62eca25
Revises: f40cc299812b
Create Date: 2024-07-17 12:15:12.045849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748af62eca25'
down_revision = 'f40cc299812b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_authors_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_authors_name'), type_='unique')

    # ### end Alembic commands ###
